### ISSUE TITLE
Wrong path to test data in README

### ISSUE THREAD

**Issue by Theresa-S** [rosalindfranklininstitute/RedLionfish#14]
Minor problem, but got me confused for some minutes...
In the Readme is the following information:
![grafik](https://user-images.githubusercontent.com/61883896/208860767-dcb02c79-d980-48ee-9560-43c8b40d0253.png)

However, it's in the scripts folder:
![grafik](https://user-images.githubusercontent.com/61883896/208860661-9245c08a-3f0c-4117-8760-f65275b71cd5.png)

**Comment by perdigao1** [comment]
Thanks for pointing this issue. I will resolve at next version.
