### ISSUE TITLE
Difference between doRLDeconvolutionFromFiles() and doRLDeconvolutionFromNpArrays() ?

### ISSUE THREAD

**Issue by wjnicol** [rosalindfranklininstitute/RedLionfish#17]
Hello,

I've been using RedLionFish successfully in my processing scripts. I started using doRLDeconvolutionFromFiles() as it looked easier to use for me by just pointing path of the necessary files. However, I am wondering why you advise to use doRLDeconvolutionFromNpArrays()? Is it more efficient? 

Can doRLDeconvolutionFromFiles() leverage GPU use? I see no options to do so...

Thank you,

William J Nicolas

**Comment by perdigao1** [comment]
Interesting question. Yes you can use that function and it will use the gpu by default. Currently it has no other options that adjust how the calculation is done. The disadvantage of using that function is that it restricted to *.tif files. This is an old function which I used for initial testing. Anyway it is not difficult to open tif files in pyton/notebook.

```
import tifffile
data = tifffile.imread( filename)
```

If you chose the use the doRLDeconvolutionFromNpArrays(), then you have more flexibility in the type of file you can open, but it does require some coding. [skimage.io.imread() ](https://scikit-image.org/docs/stable/api/skimage.io.html#skimage.io.imread) is a popular, and used as default in napari.

I hope this helps

**Comment by wjnicol** [comment]
Hello,

Yes this clears it out. I might switch to the NpArrays version. I am familiar with skimage.io.imread().

Thank you,
