### ISSUE TITLE
Feature request: dask array support

### ISSUE THREAD

**Issue by psobolewskiPhD** [rosalindfranklininstitute/RedLionfish#4]
I use `aicsimageio` and the `napari-aicsimageio` plugin to load files and typically load stuff as dask arrays. Using RedLionFish napari plugin if the same .tif's are imported as dask arrays, then a divide by zero is triggered:
```
data.shape = (128, 256, 256) , type(data) = <class 'dask.array.core.Array'> , data.dtype = uint16
psfdata.shape = (128, 256, 256) , type(psfdata) = <class 'dask.array.core.Array'> , psfdata.dtype = uint16
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/RedLionfishDeconv/helperfunctions.py:98: RuntimeWarning: invalid value encountered in true_divide!
```
The same data, as numpy arrays works fine, whether imported using the aicsimageio plugin or default builtin napari reader.
```
data.shape = (128, 256, 256) , type(data) = <class 'numpy.ndarray'> , data.dtype = uint16
psfdata.shape = (128, 256, 256) , type(psfdata) = <class 'numpy.ndarray'> , psfdata.dtype = uint16
```

I've only briefly used `reikna` but perhaps it's sufficient to coerce the input array to numpy?
This worked for me based on advice from @tlambert03 when playing with a different OpenCL FFT library and dask:
https://forum.image.sc/t/using-dask-arrays-with-pyopencl/56936/22?u=psobolewskiphd

**Comment by perdigao1** [comment]
This is probably extremely late to respond but I have been thinking about this for ages. napari does support dask arrays but I designed the program for only numpy inputs. It is not clear what solution you propose from the website, but the command `img = np.asarray(img)` seems to be a good option.

haesleinhuepf suggested this program to work from cl arrays directly... which I am also thinking about.

**Comment by perdigao1** [comment]
Resolved. There was also an issue with another `napari-aicsimageio` data type called xarray. Solution for now is to convert internally to numpy before trying any processing.
